apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres-container
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "notes_db"
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-storage
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: flask
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
