apiVersion: v1
kind: Service
metadata:
  name: calculateur-service
  namespace: flask
spec:
  selector:
    app: calculateur-deployment
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
